server:
  servlet:
    context-path: /api/emr/example
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml