server:
  servlet:
    context-path: /api/emr/example
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
